#!/bin/bash
#PBS -q condo05
#PBS -l select=1:ncpus=64:mem=500GB
#PBS -l walltime=168:00:00
#PBS -W group_list=x-ccast-prj-hulke
#PBS -N BUSCOprimaryScaffolds

# Load conda environment
source /mmfs1/home/brian.smart/miniconda3/bin/activate busco

#Load working directory
cd /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/HifiOmniCAssembly/busco_omnic/busco_omnic_primaryScaffolds

#Run busco
busco -i /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/HifiOmniCAssembly/yahs_scaffolding/yahs.out_scaffolds_final.fa \
      -m genome \
      -c 32 \
      -l embryophyta_odb10 \
      --offline \
      -o BUSCO_primaryOmniCScaffolds_embryophta_odb10

#Run busco
busco -i /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/HifiOmniCAssembly/yahs_scaffolding/yahs.out_scaffolds_final.fa \
       -m genome \
       -c 32 \
       -l eudicots_odb10 \
       --offline \
       -o BUSCO_primaryOmniCScaffolds_eudicots_odb10
