#!/bin/bash
#PBS -q condo05
#PBS -l select=1:ncpus=64:mem=500GB
#PBS -l walltime=168:00:00
#PBS -W group_list=x-ccast-prj-hulke
#PBS -N BUSCO_Chromosomes

# Load conda environment
source /mmfs1/home/brian.smart/miniconda3/bin/activate busco

#Load working directory
cd /mmfs1/home/brian.smart/projects/MutagenesisSmart/HudsonAlpha/BUSCOvisual/BUSCO_chromosomesOnly

#Run busco
busco -i /mmfs1/home/brian.smart/projects/MutagenesisSmart/HudsonAlpha/ChrLabels17Scaffs3Assemblies/Hap1_TrioScaffolds_10Mb_6seqs_ChromosomeLabels.fa \
      -m genome \
      -c 64 \
      -l embryophyta_odb10 \
      --offline \
      -o BUSCO_Hap1Chr6_embryophta_odb10

#Run busco
busco -i /mmfs1/home/brian.smart/projects/MutagenesisSmart/HudsonAlpha/ChrLabels17Scaffs3Assemblies/Hap1_TrioScaffolds_10Mb_6seqs_ChromosomeLabels.fa \
       -m genome \
       -c 64 \
       -l eudicots_odb10 \
       --offline \
       -o BUSCO_Hap1Chr6_eudicots_odb10

#Run busco
busco -i /mmfs1/home/brian.smart/projects/MutagenesisSmart/HudsonAlpha/ChrLabels17Scaffs3Assemblies/Hap2_TrioChromosomes_10Mb_17seqs_ChromosomeLabels.fa \
      -m genome \
      -c 64 \
      -l embryophyta_odb10 \
      --offline \
      -o BUSCO_Hap2Chr17_embryophta_odb10

#Run busco
busco -i /mmfs1/home/brian.smart/projects/MutagenesisSmart/HudsonAlpha/ChrLabels17Scaffs3Assemblies/Hap2_TrioChromosomes_10Mb_17seqs_ChromosomeLabels.fa \
       -m genome \
       -c 64 \
       -l eudicots_odb10 \
       --offline \
       -o BUSCO_Hap2Chr17_eudicots_odb10

#Run busco
busco -i /mmfs1/home/brian.smart/projects/MutagenesisSmart/HudsonAlpha/ChrLabels17Scaffs3Assemblies/Primary_OmniCScaffolds_10Mb_17seqs_ChromosomeLabels.fa \
      -m genome \
      -c 64 \
      -l embryophyta_odb10 \
      --offline \
      -o BUSCO_PrimaryChr17_embryophta_odb10

#Run busco
busco -i /mmfs1/home/brian.smart/projects/MutagenesisSmart/HudsonAlpha/ChrLabels17Scaffs3Assemblies/Primary_OmniCScaffolds_10Mb_17seqs_ChromosomeLabels.fa \
       -m genome \
       -c 64 \
       -l eudicots_odb10 \
       --offline \
       -o BUSCO_PrimaryChr17_eudicots_odb10
