#!/bin/bash
#PBS -q default
#PBS -l select=1:ncpus=16:mem=64GB
#PBS -l walltime=24:00:00
#PBS -W group_list=x-ccast-prj-hulke

cd /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha

/mmfs1/projects/brent.hulke/Software/fastp -i KYEN_PCRfree_1_1_CAGTAGGC_Sunflower_2_Homo_Red_I1373L2_L2_R1.fastq.gz -I KYEN_PCRfree_1_1_CAGTAGGC_Sunflower_2_Homo_Red_I1373L2_L2_R2.fastq.gz -o Sunflower_2_Homo_Red_R1.fq.gz -O Sunflower_2_Homo_Red_R2.fastq.gz

/mmfs1/projects/brent.hulke/Software/fastp -i KYEP_PCRfree_1_1_TGACGAAT_Sunflower_3_Homo_Green_I1373L2_L2_R1.fastq.gz -I KYEP_PCRfree_1_1_TGACGAAT_Sunflower_3_Homo_Green_I1373L2_L2_R2.fastq.gz -o Sunflower_3_Homo_Green_R1.fq.gz -O Sunflower_3_Homo_Green_R2.fastq.gz
