#!/bin/bash
#PBS -q bigmem
#PBS -l select=1:ncpus=36:mem=300GB
#PBS -l walltime=168:00:00
#PBS -W group_list=x-ccast-prj-hulke
#PBS -N MerquryOmniCContigs

# Load modules
module load samtools/1.20
module load r/4.4.0
module load bedtools/2.30.0

# Set directory
cd /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/HifiOmniCAssembly/merqury_omnic/merqury_primaryContigs

export MERQURY=/mmfs1/projects/brent.hulke/Software/merqury
export PATH="/mmfs1/projects/brent.hulke/Software/meryl-1.4.1/bin:$PATH"

$MERQURY/merqury.sh /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/hifi_kmers_k21.meryl \
    /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/HifiOmniCAssembly/gfatools_omnic/Sunflower_1_Hetero_Red_withOmniC.asm.hic.p_ctg.fasta \
    MerquryPrimaryContigs
