#!/bin/bash
#PBS -q bigmem
#PBS -l select=1:ncpus=64:mem=500GB
#PBS -l walltime=168:00:00
#PBS -W group_list=x-ccast-prj-hulke
#PBS -N CreatingContactMatrixScaffolding

cd /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/HifiOmniCAssembly/contact_matrix_scaffolding

source /mmfs1/home/senta.kryzer/miniconda3/bin/activate pretext_snapshot_env

PretextSnapshot -m map_omnic_pretext_scaffolding \
                -f "png"