#!/bin/bash
#PBS -q bigmem
#PBS -l select=1:ncpus=32:mem=250GB
#PBS -l walltime=168:00:00
#PBS -W group_list=x-ccast-prj-hulke
#PBS -N TidkSearchFun


source /mmfs1/home/senta.kryzer/miniconda3/bin/activate tidk_env

cd /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/HifiParentalIlluminaOmniCAssembly/tidk_telomere_check

tidk search --string TTTAGGG --dir /mmfs1/projects/brent.hulke/MutagenesisSmart/HudsonAlpha/HifiParentalIlluminaOmniCAssembly/tidk_telomere_check --output tidk_search_hap1 --fasta yahs.out_scaffolds_final_hap1.fa   